title: Data Science Portfolio
description: Documenting my learning in Data Structures
theme: jekyll-theme-minimal
logo: ./profile.png
author: Stephen Heagarty
show_downloads: false
github:
  is_project_page: false
social_links:
  github_username: StephenHeagarty
  linkedin_username: stephen-heagarty-4399a5436
  LinkedIn: https://www.linkedin.com/in/stephen-heagarty-4399a5436/
